---
title: "ODI-3"
output: html_document
date: "2023-03-20"
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(tinytex)
library(gridExtra)
library(cricketdata)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(out.width = "60%",fig.align='center')
```

```{r}
odi_wc <- read.csv("~/Downloads/odi_wc.csv") %>% na.omit
odi_wc$year <- substr(odi_wc$date, 1, 4)
```

```{r}
odi_wc %>% ggplot() + 
  geom_density(aes(x = top_runs_pct), fill = "skyblue", alpha = 0.3) + 
  geom_density(aes(x = middle_runs_pct), fill = "darkred", alpha = 0.3) +
  labs(x = "Percent of Runs", y = "Density") +
  theme_bw()

odi_wc %>% ggplot() + 
  geom_density(aes(x = top_time_pct), fill = "skyblue", alpha = 0.3) + 
  geom_density(aes(x = middle_time_pct), fill = "darkred", alpha = 0.3) +
  labs(x = "Percent of Time", y = "Density") +
  theme_bw()
```


```{r}
odi_wc %>% ggplot(aes(top_runs_pct)) + 
  geom_histogram(color = "black", fill = "skyblue") +
  labs(x = "Percent of Runs for Top Order", y = "Count") +
  theme_bw() +
  facet_wrap(year ~.)

odi_wc %>% ggplot(aes(middle_runs_pct)) + 
  geom_histogram(color = "black", fill = "skyblue") +
  labs(x = "Percent of Runs for Middle Order", y = "Count") +
  theme_bw() +
  facet_wrap(year ~.)
```
```{r}
odi_wc %>% ggplot(aes(top_time_pct)) + 
  geom_histogram(color = "black", fill = "skyblue") +
  labs(x = "Percent of Time for Top Order", y = "Count") +
  theme_bw() +
  facet_wrap(year ~.)

odi_wc %>% ggplot(aes(middle_time_pct)) + 
  geom_histogram(color = "black", fill = "skyblue") +
  labs(x = "Percent of Time for Middle Order", y = "Count") +
  theme_bw() +
  facet_wrap(year ~.)
```

```{r}
temp1 <- odi_wc %>% ggplot(aes(top_sr)) + 
  geom_boxplot(color = "black", fill = "skyblue") + 
  scale_x_continuous(limits = c(0, 250), breaks = seq(0,250, 50)) +
  labs(x = "Top Order Strike Rate") +
  theme_bw()

temp2 <- odi_wc %>% ggplot(aes(middle_sr)) + 
  geom_boxplot(color = "black", fill = "red") + 
  scale_x_continuous(limits = c(0, 250), breaks = seq(0,250, 50)) +
  labs(x = "Middle Order Strike Rate") +
  theme_bw()

grid.arrange(temp1, temp2)
```

```{r}
odi_wc %>%
  ggplot(aes(x = mov)) + 
  geom_boxplot(fill = "skyblue", color = "black") + 
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "Margin of Victory") +
  theme_bw()

which(odi_wc$mov > 0.78)

odi_wc[c(14, 27),]
```
```{r}
test_stat <- mean(odi_wc$mov, na.rm = T)

set.seed(653)
mov_sample <- sample(odi_wc$mov,size=60,replace=FALSE)

#initiate empty vector
results <- data.frame(avg=rep(NA,1000))

#repeat sampling process 1000 times and save results
for(i in 1:1000){
  
  set.seed(i)
  results$avg[i] <- mean(sample(mov_sample,size=200,replace=TRUE))

}

#plot sampling distribution
ggplot(data=results,aes(x=avg)) +
  geom_histogram(color='black',fill='sky blue',bins=32) +
  labs(title='Sampling Distribution', x='Sample Mean MOV',y='Count') +
  geom_vline(xintercept=test_stat,color='red',size=1)
  theme_bw() 
  
quantile(results$avg,0.025)
quantile(results$avg,0.975)
```


```{r}
odi_wc[,c(-1,-2,-16)] %>%
  cor()
```

