---
title: "ODI-2"
output: html_document
date: "2023-03-19"
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(tinytex)
library(cricketdata)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(out.width = "60%",fig.align='center')
```

```{r}
wc_player_data <- read.csv("~/Downloads/player_data.csv")
wc_matches_up <- read.csv("~/Downloads/wc_matches.csv")
```

```{r}
odi_matches <- fetch_cricsheet("match", "male", "odis")
odi_players <- fetch_cricsheet("player", "male", "odis")
wc_matches <- odi_matches %>% filter(event %in% c("ICC World Cup", "ICC Cricket World Cup", "World Cup"))
```

```{r}
wc_matches$winner_wickets <- as.numeric(wc_matches$winner_wickets)
wc_matches$winner_runs <- as.numeric(wc_matches$winner_runs)
wc_matches$match_id <- as.numeric(wc_matches$match_id)
```

```{r}
temp <- wc_matches_up %>% select(match_id, balls_remaining)
wc_matches <- left_join(wc_matches, temp, "match_id")
```

```{r}
top_order_runs <- wc_player_data %>% group_by(match_id) %>% 
                                     filter(Pos %in% c(1, 2, 3)) %>% 
                                     summarize(inns_1 = sum(Runs[Inns == 1], na.rm = TRUE), 
                                               inns_2 = sum(Runs[Inns == 2], na.rm = TRUE))

middle_order_runs <- wc_player_data %>% group_by(match_id) %>% 
                                        filter(Pos %in% c(4, 5, 6, 7)) %>% 
                                        summarize(inns_1 = sum(Runs[Inns == 1], na.rm = TRUE), 
                                                  inns_2 = sum(Runs[Inns == 2], na.rm = TRUE))
```

```{r}
top_order_mins <- wc_player_data %>% group_by(match_id) %>% 
                                     filter(Pos %in% c(1, 2, 3)) %>% 
                                     summarize(inns_1 = sum(Mins[Inns == 1], na.rm = TRUE), 
                                               inns_2 = sum(Mins[Inns == 2], na.rm = TRUE))

middle_order_mins <- wc_player_data %>% group_by(match_id) %>% 
                                        filter(Pos %in% c(4, 5, 6, 7)) %>% 
                                        summarize(inns_1 = sum(Mins[Inns == 1], na.rm = TRUE), 
                                                  inns_2 = sum(Mins[Inns == 2], na.rm = TRUE))
```

```{r}
top_order_bf <- wc_player_data %>% group_by(match_id) %>% 
                                   filter(Pos %in% c(1, 2, 3)) %>% 
                                   summarize(inns_1 = sum(BF[Inns == 1], na.rm = TRUE), 
                                             inns_2 = sum(BF[Inns == 2], na.rm = TRUE))

middle_order_bf <- wc_player_data %>% group_by(match_id) %>% 
                                      filter(Pos %in% c(4, 5, 6, 7)) %>% 
                                      summarize(inns_1 = sum(BF[Inns == 1], na.rm = TRUE), 
                                                inns_2 = sum(BF[Inns == 2], na.rm = TRUE))
```

```{r}
top_order_x4 <- wc_player_data %>% group_by(match_id) %>% 
                                   filter(Pos %in% c(1, 2, 3)) %>% 
                                   summarize(inns_1 = sum(X4s[Inns == 1], na.rm = TRUE), 
                                             inns_2 = sum(X4s[Inns == 2], na.rm = TRUE))

middle_order_x4 <- wc_player_data %>% group_by(match_id) %>% 
                                      filter(Pos %in% c(4, 5, 6, 7)) %>% 
                                      summarize(inns_1 = sum(X4s[Inns == 1], na.rm = TRUE), 
                                                inns_2 = sum(X4s[Inns == 2], na.rm = TRUE))
```

```{r}
top_order_x6 <- wc_player_data %>% group_by(match_id) %>% 
                                   filter(Pos %in% c(1, 2, 3)) %>% 
                                   summarize(inns_1 = sum(X6s[Inns == 1], na.rm = TRUE), 
                                             inns_2 = sum(X6s[Inns == 2], na.rm = TRUE))

middle_order_x6 <- wc_player_data %>% group_by(match_id) %>% 
                                      filter(Pos %in% c(4, 5, 6, 7)) %>% 
                                      summarize(inns_1 = sum(X6s[Inns == 1], na.rm = TRUE), 
                                                inns_2 = sum(X6s[Inns == 2], na.rm = TRUE))
```

```{r}
top_order_SR <- wc_player_data %>% group_by(match_id) %>% 
                                   filter(Pos %in% c(1, 2, 3)) %>% 
                                   summarize(inns_1 = mean(SR[Inns == 1], na.rm = TRUE), 
                                             inns_2 = mean(SR[Inns == 2], na.rm = TRUE))

middle_order_SR <- wc_player_data %>% group_by(match_id) %>% 
                                      filter(Pos %in% c(4, 5, 6, 7)) %>% 
                                      summarize(inns_1 = mean(SR[Inns == 1], na.rm = TRUE), 
                                                inns_2 = mean(SR[Inns == 2], na.rm = TRUE))
```

```{r}
wicket_resource <- wc_matches %>% filter(!is.na(winner_wickets)) %>% 
  select(match_id, winner_wickets)

wickets_mov <- c()

for (i in wicket_resource$winner_wickets){
  if (i == 10) {
    wickets_mov <- rbind(wickets_mov, 1)
  } else if (i == 9) {
    wickets_mov <- rbind(wickets_mov, 0.825)
  } else if (i == 8) {
    wickets_mov <- rbind(wickets_mov, 0.611)
  } else if (i == 7) {
    wickets_mov <- rbind(wickets_mov, 0.546)
  } else if (i == 6) {
    wickets_mov <- rbind(wickets_mov, 0.42)
  } else if (i == 5) {
    wickets_mov <- rbind(wickets_mov, 0.312)
  } else if (i == 4) {
    wickets_mov <- rbind(wickets_mov, 0.226)
  } else if (i == 3) {
    wickets_mov <- rbind(wickets_mov, 0.156)
  } else if (i == 2) {
    wickets_mov <- rbind(wickets_mov, 0.098)
  } else if (i == 1) {
    wickets_mov <- rbind(wickets_mov,0.047)
  } else if (i == 0) {
    wickets_mov <- rbind(wickets_mov, 0)
  }
}

wicket_resource <- wicket_resource %>% summarize(match_id = match_id, wickets_mov = wickets_mov)
  
```

```{r}
ball_resource <- wc_matches %>% filter(!is.na(balls_remaining)) %>% 
  select(match_id, balls_remaining) %>% 
  summarize(match_id = match_id, balls_mov = balls_remaining/300)

total_balls <- wc_player_data %>% group_by(match_id) %>% 
  filter(Inns == 1) %>% 
  summarize(match_id = match_id, total_balls = sum(BF, na.rm = TRUE)) %>%
  unique() 

top_bf_resource <- left_join(total_balls, top_order_bf, "match_id") %>%
  summarize(match_id = match_id, top_bf_pct = inns_1/total_balls)

middle_bf_resource <- left_join(total_balls, middle_order_bf, "match_id") %>%
  summarize(match_id = match_id, middle_bf_pct = inns_1/total_balls)
```

```{r}
target <- wc_player_data %>% group_by(match_id) %>% 
  filter(Inns == 1) %>% 
  summarize(match_id = match_id, target = sum(Runs, na.rm = TRUE)) %>%
  unique()

temp2 <- wc_matches %>% select(match_id, winner_runs)

run_resource <- left_join(target, temp2, "match_id") %>%
  summarize(match_id = match_id, run_mov = winner_runs/target)
```

```{r}
total_time <- wc_player_data %>% group_by(match_id) %>% 
  filter(Inns == 1) %>% 
  summarize(match_id = match_id, total_time = sum(Mins, na.rm = TRUE)) %>%
  unique()

top_time_resource <- left_join(total_time, top_order_mins, "match_id") %>%
  summarize(match_id = match_id, top_time_pct = inns_1/total_time)

middle_time_resource <- left_join(total_time, middle_order_mins, "match_id") %>%
  summarize(match_id = match_id, middle_time_pct = inns_1/total_time)
```


```{r}
temp3 <- merge(wicket_resource, ball_resource, "match_id")
limit_resource <- temp3 %>% summarize(match_id = match_id, inns_2_mov = ifelse(wickets_mov > balls_mov, balls_mov, wickets_mov))

top_order_resource <- merge(top_order_runs, target) %>%
  summarize(match_id = match_id, top_order_pct = inns_1/target)

middle_order_resource <- merge(middle_order_runs, target) %>%
  summarize(match_id = match_id, middle_order_pct = inns_1/target)

merge(top_order_resource, middle_order_resource, "match_id") %>%
  summarize(match_id = match_id, top_order_pct = top_order_pct, middle_order_pct = middle_order_pct, x = top_order_pct + middle_order_pct)
```

```{r}
total_4 <- wc_player_data %>% group_by(match_id) %>% 
  filter(Inns == 1) %>% 
  summarize(match_id = match_id, total_4 = sum(X4s, na.rm = TRUE)) %>%
  unique()

top_4_resource <- left_join(total_4, top_order_x4, "match_id") %>%
  summarize(match_id = match_id, top_4_pct = inns_1/total_4)

total_6 <- wc_player_data %>% group_by(match_id) %>% 
  filter(Inns == 1) %>% 
  summarize(match_id = match_id, total_6 = sum(X6s, na.rm = TRUE)) %>%
  unique()

top_6_resource <- left_join(total_6, top_order_x6, "match_id") %>%
  summarize(match_id = match_id, top_6_pct = inns_1/total_6)
```


```{r}
wc_matches_final <- full_join(run_resource, limit_resource, "match_id")
```




