---
title: "temp"
output: html_document
date: "2023-04-05"
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(tinytex)
library(cricketdata)
library(leaps)
```

```{r}
odi <- read.csv("~/Downloads/odi.csv")
odi$date <- as.Date(odi$date)
odi$date <- format(odi$date, "%Y")
odi <- rename(odi, year = date)
```

```{r}
round(cor(odi[, 6:20]), 2)
```

```{r}
odi %>% group_by(year) %>% 
        summarize(to_mins_pct = round(cor(to_mins_pct, mov), 2),
                  mo_mins_pct = round(cor(mo_mins_pct, mov), 2),
                  pct_4s = round(cor(pct_4s, mov), 2),
                  pct_6s = round(cor(pct_6s, mov), 2),
                  to_sr = round(cor(to_sr, mov), 2),
                  mo_sr = round(cor(mo_sr, mov), 2),
                  pct_mdns = round(cor(pct_mdns, mov), 2),
                  wkts = round(cor(wkts, mov), 2),
                  econ = round(cor(econ, mov), 2))
```

```{r}
qualified <- c("Afghanistan", "Australia", "Bangladesh", "England", "India",
               "New Zealand", "Pakistan", "South Africa", "Sri Lanka", "West Indies")

team_cor <- odi %>% group_by(team1) %>% 
                    summarize(to_mins_pct = round(cor(to_mins_pct, mov), 2),
                    mo_mins_pct = round(cor(mo_mins_pct, mov), 2),
                    pct_4s = round(cor(pct_4s, mov), 2),
                    pct_6s = round(cor(pct_6s, mov), 2),
                    to_sr = round(cor(to_sr, mov), 2),
                    mo_sr = round(cor(mo_sr, mov), 2),
                    pct_mdns = round(cor(pct_mdns, mov), 2),
                    wkts = round(cor(wkts, mov), 2),
                    econ = round(cor(econ, mov), 2))

team_cor %>% filter(team1 %in% qualified)
```

```{r}
model_bwd <- regsubsets(mov~.,data=odi[, 6:20],method='backward',nvmax=14)
summary(model_bwd)$adjr2
summary(model_bwd)$outmat
```

```{r}
train_set <- odi %>% filter(year %in% c(2003, 2007, 2011, 2015))
train_set <- train_set[, 6:20]
```

```{r}
test_set <- odi %>% filter(year == 2019)
test_set <- test_set[, 6:20]
```

```{r}
model_1 <- lm(mov~., data=train_set)
summary(model_1)
```

```{r}
predictions <- predict(model_1, test_set)
rmse <- sqrt(mean((test_set$mov - predictions)^2))
rmse
```

```{r}
#create empty vector to hold accuracies
rmse <- data.frame(class_acc=rep(NA,14))

for (i in 1:14) {

  #remove i-th variable
  train_min1 <- train_set[,-i]
  
  #fit model minus one variable
  model_min1 <- lm(mov~.,data=train_min1)
  
  #classify testing observations
  test_min1 <- test_set %>%
    mutate(preds=predict(model_min1,newdata=test_set))
  
  #compute and save overall accuracy
  rmse$vals[i] <- sqrt(mean((test_set$mov - test_min1$preds)^2))
}
```

```{r}
#permanently remove one variable
train_min1 <- train_set[,-10]

#create empty vector to hold accuracies
rmse2 <- data.frame(class_acc=rep(NA,13))

for (i in 1:13) {

  #remove i-th variable
  train_min2 <- train_min1[,-i]
  
  #fit model minus one variable
  model_min2 <- lm(mov~.,data=train_min2)
  
  #classify testing observations
  test_min2 <- test_set %>%
    mutate(preds=predict(model_min2,newdata=test_set))
  
  #compute and save overall accuracy
  rmse2$vals[i] <- sqrt(mean((test_set$mov - test_min2$preds)^2))
}
```

```{r}
#permanently remove one variable
train_min2 <- train_min1[,-10]

#create empty vector to hold accuracies
rmse3 <- data.frame(class_acc=rep(NA,12))

for (i in 1:12) {

  #remove i-th variable
  train_min3 <- train_min2[,-i]
  
  #fit model minus one variable
  model_min3 <- lm(mov~.,data=train_min3)
  
  #classify testing observations
  test_min3 <- test_set %>%
    mutate(preds=predict(model_min3,newdata=test_set))
  
  #compute and save overall accuracy
  rmse3$vals[i] <- sqrt(mean((test_set$mov - test_min3$preds)^2))
}
```

```{r}
#permanently remove one variable
train_min3 <- train_min2[,-5]

#create empty vector to hold accuracies
rmse4 <- data.frame(class_acc=rep(NA,11))

for (i in 1:11) {

  #remove i-th variable
  train_min4 <- train_min3[,-i]
  
  #fit model minus one variable
  model_min4 <- lm(mov~.,data=train_min4)
  
  #classify testing observations
  test_min4 <- test_set %>%
    mutate(preds=predict(model_min4,newdata=test_set))
  
  #compute and save overall accuracy
  rmse4$vals[i] <- sqrt(mean((test_set$mov - test_min4$preds)^2))
}
```

```{r}
#permanently remove one variable
train_min4 <- train_min3[,-7]

#create empty vector to hold accuracies
rmse5 <- data.frame(class_acc=rep(NA,10))

for (i in 1:10) {

  #remove i-th variable
  train_min5 <- train_min4[,-i]
  
  #fit model minus one variable
  model_min5 <- lm(mov~.,data=train_min5)
  
  #classify testing observations
  test_min5 <- test_set %>%
    mutate(preds=predict(model_min5,newdata=test_set))
  
  #compute and save overall accuracy
  rmse5$vals[i] <- sqrt(mean((test_set$mov - test_min5$preds)^2))
}
```

```{r}
#permanently remove one variable
train_min5 <- train_min4[,-4]

#create empty vector to hold accuracies
rmse6 <- data.frame(class_acc=rep(NA,9))

for (i in 1:9) {

  #remove i-th variable
  train_min6 <- train_min5[,-i]
  
  #fit model minus one variable
  model_min6 <- lm(mov~.,data=train_min6)
  
  #classify testing observations
  test_min6 <- test_set %>%
    mutate(preds=predict(model_min6,newdata=test_set))
  
  #compute and save overall accuracy
  rmse6$vals[i] <- sqrt(mean((test_set$mov - test_min6$preds)^2))
}
```

```{r}
model_odi <- lm(mov~., data=train_min5)
summary(model_odi)

predictions <- predict(model_odi, test_set)
rmse <- sqrt(mean((test_set$mov - predictions)^2))
rmse/(max(odi$mov) - min(odi$mov))

test_set %>% ggplot(aes(x = seq(1:nrow(test_set)), y = mov)) + geom_point() + geom_smooth(method = lm, se = F) 
#plot(test_set$mov) + abline(model_odi)
```
```{r}
final_set <- odi %>% select(to_runs_pct, mo_runs_pct, to_mins_pct, mo_bf_pct, pct_4s, to_sr, pct_mdns, wkts, econ, mov)

predictions <- predict(model_odi, final_set)
rmse <- sqrt(mean((final_set$mov - predictions)^2))
rmse/(max(odi$mov) - min(odi$mov))
```




